version: '3'
services:
        dbos:
                image: mysql:5.7
                volumes:
                        - mysql_drive:/var/lib/mysql
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_USER: ayush
                        MYSQL_PASSWORD: redhat
                        MYSQL_DATABASE: mydb
                restart: always
	wpos:
                image: wordpress:5.1.1-php7.3-apache
                restart: always
                depends_on:
                        - dbos
                ports:
                        - 8081:80
                environment:
                        WORDPRESS_DB_HOST: dbos
                        WORDPRESS_DB_USER: ayush
                        WORDPRESS_DB_PASSWORD: redhat
                        WORDPRESS_DB_NAME: mydb
                       
                volumes:
                        - wordpress_drive:/var/www/html
